[[language]]
name = "python"
language-servers = [ "pylsp" ]
auto-format = true

[language-server.pylsp]
command = "pylsp-hx"

[language-server.pylsp.config.pylsp.plugins]
autopep8.enabled = false
flake8.enabled = false
jedi_symbols.include_import_symbols = true
jedi_completion.enabled = true
mccabe.enabled = false
preload.enabled = false
pycodestyle.enabled = false
pyflakes.enabled = false
pylint.enabled = false
rope_autoimport.enabled = false
rope_autoimport.completions.enabled= false
rope_autoimport.code_actions.enabled= false
rope_completion.enabled = false
yapf.enabled = false

[language-server.pylsp.config.ruff]
plugins.pyls_ruff.enabled = true

[[language]]
name = "html"
language-servers = ["superhtml"]
auto-format = true

[language-server.superhtml]
command = "superhtml"
args = ["lsp"]

[[language]]
name = "c"
language-servers = ["clangd"]
auto-format = true

[[language]]
name = "boron"
scope = "text.rebol"
file-types = ["b"]
comment-tokens = [";"]
block-comment-tokens = {start = "/*", end = "*/"}
indent = {tab-width=2, unit="  "}
